using System;
using System.IO;

namespace ManiaECS_Generator.Systems
{
	public class GetQueryFileSystem : SystemBase
	{		
		protected override void OnGeneratorPass(bool calledOneTime)
		{
			
		}

		public (string structHeader, string bottom) GetQueryResult()
		{
			var inputDirectory = World.GetSystem<IOFolderSystem>().InputDirectory;
			if (!File.Exists(inputDirectory + "/query.txt"))
				return (null, null);
			
			Logger.WriteInfo("Query", "Started getting queries...");

			var lines = File.ReadAllLines(inputDirectory + "/query.txt");
			string structHeader = string.Empty, bottom = string.Empty;
			foreach (var str in lines)
			{
				var structNames = str.Replace(" ", string.Empty)
				                     .Split(',', StringSplitOptions.RemoveEmptyEntries);
				var headerInside = string.Empty;
				var functionArgument = string.Empty;
				var queryStruct = string.Empty;
				var condition = string.Empty;
				var getData = string.Empty;
				var function = string.Empty;
				
				queryStruct += "#Struct QueryResult";

				var structFound = 0;
				for (var i = 0; i < structNames.Length; i++)
				{
					var name = structNames[i];
					if (name.StartsWith("//"))
						continue;
						
					queryStruct      += $"_{name}";
					headerInside     += $"\n{name} _{name};";
					functionArgument += $"{name} _{i}, ";
					condition += $"&& Has(entity, {name} {{}})";
					getData += $"if (Has(entity, {name} {{}})) queryResult._{name} = Get(entity, {name} {{}}); else continue;\n\t\t";
					
					structFound++;
				}

				if (structFound == 0)
					continue;

				var queryName = queryStruct.Replace("#Struct ", string.Empty);

				function += $"declare {queryName}[] Cached_{queryName};\n";
				function += $"declare SEntity[] Cached_Entities_{queryName};\n";
				function += $@"SEntity[] GetAllEntities({functionArgument.Remove(functionArgument.Length - 2, 2)})
{{
	Cached_Entities_{queryName}.clear();

	declare entities = EntityManager::GetEntities();
	foreach (entity in entities)
	{{
		if (True {condition})
		{{
			Cached_Entities_{queryName}.add(entity);
		}}
	}}

	return Cached_Entities_{queryName};
}}
";
				function += $@"{queryName}[] GetAllData({functionArgument.Remove(functionArgument.Length - 2, 2)})
{{
	Cached_{queryName}.clear();

	declare entities = EntityManager::GetEntities();
	foreach (entity in entities)
	{{
		declare queryResult = {queryName} {{}};
		{getData}

		Cached_{queryName}.add(queryResult);
	}}

	return Cached_{queryName};
}}
";

				queryStruct += $@"{{
	// This was autogenerated.{headerInside}
}}";

				structHeader += queryStruct;
				bottom += function;
			}

			return (structHeader, bottom);
		}
	}
}